name: kalenderwoche
base: core20
version: '0.1'
summary: Show the kalenderwoche for a date
description: |
    Finde die kalenderwoche für ein bestimmtes Datum heraus.
grade: stable
confinement: strict

parts:
    kalenderwoche:
        plugin: python
        source: .

apps:
    kalenderwoche:
        command: bin/kalenderwoche.py
